# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- echo | gem --version
- gem install activesupport        # yeah, it works if you install it beforehand
- apt-get install -y zlib1g-dev ruby-execjs
- gem install github-pages

- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=DopamineKit
script:
- set -o pipefail && xcodebuild test -workspace Example/Workspace.xcworkspace -scheme YourApp-Example -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
