# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=DopamineKit
script:
- set -o pipefail && xcodebuild test -workspace YourApp/DopamineKit.xcworkspace -scheme YourApp-Example -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
